name: Release

on:
  push:
    branches: [ "release" ]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install -g pnpm
    - name: Build
      run: |
        cd front
        pnpm install
        npm run build
    - name: Upload generated web template
      uses: actions/upload-artifact@v4
      id: upload-generated-template
      with:
        name: template-output
        path: front/dist/
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'site'
    - name: Setup git config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "sankooc@163.com"
    - name: clean
      run: |
        rm -rf dist
    - name: Download generated template
      uses: actions/download-artifact@v4
      with:
        name: template-output
        path: dist
    - name: Commit and push
      run: |
        git add .
        git commit -m "auto release"
        git push origin site -f